#!/usr/bin/python3

# This file simulate the behavior of the true METROPOLIS2 simulator, for testing
# purposes only.
import os
import sys
import getopt
import json
import time

def main(argv):
    inputfile = None
    outputdir = '.'
    try:
        opts, args = getopt.getopt(argv, "i:o:", ["input=","output="])
    except getopt.GetoptError:
        print('dummy_simulator.py -i <inputfile> [-o <outputdir>]')
        sys.exit(2)
    for opt, arg in opts:
        if opt in ("-i", "--input"):
            inputfile = arg
        elif opt in ("-o", "--output"):
            outputdir = arg

    if inputfile is None:
        print('dummy_simulator.py -i <inputfile> [-o <outputdir>]')
        sys.exit(2)

    try:
        with open(inputfile) as f:
            data = json.load(f)
    except:
        print('Failed to read input file: {}'.format(inputfile))
        sys.exit(2)

    if not os.path.isdir(outputdir):
        try:
            os.mkdir(outputdir)
        except:
            print('Failed to create output direction: {}'.format(outputdir))

    for i in range(1, 11):
        time.sleep(2)
        with open(os.path.join(outputdir, f'iteration{i}.json'), 'w') as f:
            f.write('{}')

    with open(os.path.join(outputdir, f'results.json'), 'w') as f:
        f.write('{}')


if __name__ == "__main__":
    main(sys.argv[1:])
