from django.urls import path
from .views import (create_project, delete_nodes, delete_roads_types,
                    create_network, create_roadtype,
                    project_details, update_network, update_project,
                    delete_project, network_details, index,
                    delete_network, visualization, edges_point_geojson,
                    edges_table, nodes_table, road_type_table,
                    create_zoneset, zoneset_details, update_zoneset,
                    delete_zoneset, zones_table,
                    create_od_matrix, od_matrix_details, update_od_matrix,
                    delete_od_matrix, od_pair_table,
                    fetch_task,
                    )
from metro_app.vehicle.views import (upload_vehicle, add_vehicle,
                                     update_vehicle, delete_vehicle,
                                     create_vehicle_set, vehicle_set_details,
                                     update_vehicle_set, delete_vehicle_set)
from metro_app.preferences.views import (add_preferences, upload_preferences,
                                         update_preferences, delete_preferences)
from metro_app.population.views import (add_population, update_population,
                                        population_details,
                                        create_population_segment,
                                        update_population_segment,
                                        delete_population_segment,
                                        population_segment_details,
                                        generate_agents_input)
from metro_app.network.views import (create_network2, update_network2,
                                     network2_details, upload_zone_node_relation)
from metro_app.agent.views import (add_agent, upload_agent)
from metro_app.parameters.views import (set_parameters, upload_parameters)
from metro_app.run.views import (create_run, run_details, delete_run, generate_run_input)
from .networks import (upload_edge, upload_node, upload_road_type, upload_zone,
                       upoload_od_pair,)
from .metrosim import upload_edges_results


urlpatterns = [
     path('', index, name='home'),
     path('network/<str:pk>/delete/nodes', delete_nodes, name='delete_nodes'),
     path('network/<str:pk>/delete/road_types', delete_roads_types,
          name='delete_roads_types'),
     path('project/', create_project, name='create_project'),
     path('project/<str:pk>/', project_details, name='project_details'),
     path('update_project/<str:pk>/', update_project, name='update_project'),
     path('delete_project/<str:pk>/', delete_project, name='delete_project'),
     path('network/project/<str:pk>/', create_network, name='create_network'),
     path('update_network/<str:pk>/', update_network, name='update_network'),
     path('delete_network/<str:pk>/', delete_network, name='delete_network'),
     path('network/<str:pk>/roadtype/', create_roadtype, name='roadtype'),
     path('network/<str:pk>/details/', network_details, name='network_details'),
     path('network/<str:pk>/upload_node/', upload_node, name='upload_node'),
     path('network/<str:pk>/upload_edge/', upload_edge, name='upload_edge'),
     path('visualization/network/<str:pk>/', visualization,
          name='network_visualization'),
     path('network/<str:pk>/upload_road/', upload_road_type, name='upload_road'
          ),
     path('network/<str:pk>/edges.geojson/', edges_point_geojson),
     path('metrosim/network/<str:pk>/upload_edges_results/',
          upload_edges_results),
     path('table/network/<str:pk>/edges/', edges_table, name='edges'),
     path('table/network/<str:pk>/nodes/', nodes_table, name='nodes'),
     path('table/network/<str:pk>/roadtype/', road_type_table,
          name='roadtable'),
     path('zoneset/project/<str:pk>/', create_zoneset, name='create_zoneset'),
     path('zoneset/<str:pk>/details/', zoneset_details, name='zoneset_details'),
     path('update_zoneset/<str:pk>/', update_zoneset, name='update_zoneset'),
     path('delete_zoneset/<str:pk>/', delete_zoneset, name='delete_zoneset'),
     path('zone/<str:pk>/upload_zone/', upload_zone, name='upload_zone'),
     path('table/zoneset/<str:pk>/zones/', zones_table, name='zones'),
     path('odmatrix/project/<str:pk>/', create_od_matrix,
          name='create_od_matrix'),
     path('odmatrix/<str:pk>/details/', od_matrix_details,
          name='od_matrix_details'),
     path('update_odmatrix/<str:pk>/', update_od_matrix,
          name='update_od_matrix'),
     path('delete_od_matrix/<str:pk>/', delete_od_matrix,
          name='delete_od_matrix'),
     path('odmatrix/<str:pk>/upoload_od_pair/', upoload_od_pair,
          name='upoload_od_pair'),
     path('table/odmatrix/<str:pk>/odpair/', od_pair_table,
          name='od_pair'),
     path('task/<uuid:task_id>/', fetch_task, name='fetch_task'),
     path('vehicle/project/<str:pk>/upload_vehicle', upload_vehicle,
          name='upload_vehicle'),
     path('vehicle/project/<str:pk>/add_vehicle', add_vehicle,
          name='add_vehicle'),
     path('update_vehicle/<str:pk>/', update_vehicle, name='update_vehicle'),
     path('delete_vehicle/<str:pk>/', delete_vehicle, name='delete_vehicle'),
     path('preferences/project/<str:pk>/', add_preferences,
          name='add_preferences'),
     path('project/<str:pk>/upload_preferences/', upload_preferences,
          name='upload_preferences'),
     path('update_preferences/<str:pk>', update_preferences,
          name='update_preferences'),
     path('delete_preferences/<str:pk>/', delete_preferences,
          name='delete_preferences'),
     path('population/project/<str:pk>/', add_population,
          name='add_population'),
     path('update_population/<str:pk>/', update_population,
          name='update_population'),
     path('population/<str:pk>/details/', population_details,
          name='population_details'),
     path('create_network2/project/<str:pk>/', create_network2,
          name='create_network2'),
     path('update_network2/<str:pk>/', update_network2,
          name='update_network2'),
     path('network2/<str:pk>/details/', network2_details,
          name='network2_details'), 
     path('network/<str:pk>/upload_zone_node_relation',
          upload_zone_node_relation, name='upload_zone_node_relation'),
     path('psegment/population/<str:pk>/', create_population_segment,
          name='create_population_segment'),
     path('update_psegment/<str:pk>/', update_population_segment,
          name='update_population_segment'),
     path('delete_psegment/<str:pk>/', delete_population_segment,
          name='delete_population_segment'),
     path('psegment/<str:pk>/details/', population_segment_details,
          name='population_segment_details'),
     path('population/<str:pk>/add_agent', add_agent, name='add_agent'),
     path('population/<str:pk>/upload_agent/', upload_agent,
          name='upload_agent'),
     path('parameterset/project/<str:pk>/', set_parameters,
          name='set_parameters'),
     path('parameterset/<str:pk>/upload_parameters/', upload_parameters,
          name='upload_parameters'),
     path('project/<str:pk>/create_run/', create_run,
          name='create_run'),
     path('run/<str:pk>/details/', run_details,
          name='run_details'),
     path('run/<str:pk>/delete', delete_run,
          name='delete_run'),
     path('population/<str:pk>/generate_agent/', generate_agents_input,
          name='generate_agent'),
     path('run/<str:pk>/generate_run_input/', generate_run_input,
          name='generate_run_input'),
]
