# Generated by Django 3.1.7 on 2021-04-09 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edges',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_network', to='metro_app.roadnetwork'),
        ),
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_project', to='metro_app.project'),
        ),
        migrations.AlterField(
            model_name='odmatrix',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odmatrix_project', to='metro_app.project'),
        ),
        migrations.AlterField(
            model_name='odpair',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odpairs_destination', to='metro_app.zone'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_project', to='metro_app.project'),
        ),
    ]
